# Generated by Django 4.2.7 on 2023-11-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0002_rename_product_name_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
