# Generated by Django 4.2.7 on 2023-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0003_alter_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(max_length=200),
        ),
    ]
